jsk-ros-pkg/jsk_aerial_robot

.travis.yml, README.md, aerial_robot_base/src/aerial_robot_base.cpp, hydrus/hydrus_transform_control/CMakeLists.txt
=> Test Commit

aerial_robot_model/robots/hydrusx/hydrusx_octo.urdf.xacro, hydrus/hydrus_transform_control/config/hydrusx/octo/Hydrus.yaml, hydrus/hydrus_transform_control/config/hydrusx/octo/MotorInfo.yaml, hydrus/hydrus_transform_control/config/hydrusx/octo/PidControlConfig.yaml, hydrus/hydrus_transform_control/config/hydrusx/octo/Servo.yaml, hydrus/hydrus_transform_control/src/transform_control.cpp
@chibi314 
hydrus/hydrus_transform_control/src/transform_control.cpp はハードコーディングでバグを回避している。
=> [Hydrusx octo] Add model configuration for octo type

aerial_robot_base/config/sensor_plugin/baro.yaml, aerial_robot_base/config/sensor_plugin/gps.yaml, aerial_robot_base/config/sensor_plugin/leddar_one.yaml, aerial_robot_base/config/sensor_plugin/rtk_gps.yaml, aerial_robot_base/config/simulation/SensorFusion.yaml, aerial_robot_base/include/aerial_robot_base/basic_state_estimation.h, aerial_robot_base/include/aerial_robot_base/flight_control.h, aerial_robot_base/include/aerial_robot_base/sensor_base_plugin.h, aerial_robot_base/launch/sensors/onboard_sensors.launch, aerial_robot_base/launch/simulation.launch, aerial_robot_base/src/flight_control.cpp, aerial_robot_base/src/flight_navigation.cpp, aerial_robot_base/src/kf/baro_bias_plugin.cpp, aerial_robot_base/src/sensor/altitude.cpp, aerial_robot_base/src/sensor/gps.cpp, aerial_robot_base/src/sensor/imu.cpp, aerial_robot_base/src/sensor/mocap.cpp, aerial_robot_base/src/sensor/optical_flow.cpp, aerial_robot_base/src/state_estimation.cpp, hydrus/hydrus_transform_control/config/hydrusx/SensorFusion.yaml, hydrus/hydrus_transform_control/config/hydrusx/quad/Hydrus.yaml, hydrus/hydrus_transform_control/config/hydrusx/quad/PidControlConfig.yaml, hydrus/hydrus_transform_control/launch/hydrusx/hydrusx_bringup.launch
Add following sensors and relative fusion process to do egomotion estimation.
=> Add the state estimation for the non-mocap enviroment.

aerial_robot_base/src/sensor/optical_flow.cpp, hydrus/hydrus_transform_control/config/hydrusx/SensorFusion.yaml, hydrus/hydrus_transform_control/config/hydrusx/TeleopNavigationConfig.yaml
1. improve the outlier check way
2. update the config setting for optical flow sensor plugin
=> [Optical flow] update sensor fusion with optical flow

aerial_robot_base/include/aerial_robot_base/basic_state_estimation.h, aerial_robot_base/include/aerial_robot_base/flight_navigation.h, aerial_robot_base/include/aerial_robot_base/sensor_base_plugin.h, aerial_robot_base/msg/FlightNav.msg, aerial_robot_base/src/flight_control.cpp, aerial_robot_base/src/flight_navigation.cpp, aerial_robot_base/src/sensor/imu.cpp, aerial_robot_base/src/sensor/mocap.cpp, aerial_robot_base/src/sensor/vo.cpp, hydrus/hydrus_transform_control/config/hydrus3/TeleopNavigationConfig.yaml, hydrus/hydrus_transform_control/config/hydrusx/TeleopNavigationConfig.yaml
Improve the control-navigation system:
control mode: pos/vel/acc
control frame: world/local
=> Att control mode

aerial_robot_base/launch/external_module/mocap.launch
I changed mocap.launch to be used for multiple robots without editing.
=> robot id for mocap.launch

aerial_robot_nerve/spinal/mcu_project/Jsk_Lib/sensors/imu/imu_mpu9250.cpp, aerial_robot_nerve/spinal/mcu_project/Jsk_Lib/sensors/imu/imu_mpu9250.h
@chibi314 @kanke-hayata 
I have almost finished to implement the usage of next generation of GPS module with built-in magnetometer.
Tonight, I will attach the instruction images to show how to use and configure the new GPS, 
and also provide two prepared GPS module for your outdoor experiment (two hydrus).
=> Refactor interface in spinal to handle more external magnetometer built in GPS module

robots/hydrus_xi/urdf/link.urdf.xacro
Re-created https://github.com/JSKAerialRobot/aerial_robot/pull/438/files
I hope this time it is able to merge because the parent commit (current master) passed Travis.
=> fix gimbal link module weight (again)

.travis.sh
Add "--include-eol-distros" option for rosdep to allow building for ros-kinetic distro
=> Support CI for EOL ros kinetic distro 

aerial_robot_control/include/aerial_robot_control/flight_navigation.h
enable acc nav mode via teleop_command/ctrl_mode
=> enable acc nav mode via teleop_command/ctrl_mode

robots/dragon/robots/quad/euclid_201709.urdf.xacro
fix name in dragon xacro model: `hydrus` -> `dragon`
=> [dragon] fix name in dragon.urdf.xacro

.travis.sh
Fix the repository name from `aerial_robot` to `jsk_aerial_robot`
=> Correct the repository name for travis CI

.github/workflows/ci.yml, .travis.sh, .travis.yml
Enable CI by Github Action using same [.travis.sh](https://github.com/tongtybj/aerial_robot/blob/462c4d2224076524d23ab18b0e9f74fe365f9453/.travis.sh)
=> Add github action CI

aerial_robot_nerve/motor_test/README.md
The README.md for motor testing has been changed to be more detail.
=> modified README.md for motor test.

.github/workflows/python3.yml
The python version for python3 check was wrong. So far the github action check for python3 was not correct.
=> Fix the wrong python version in python3 check script

aerial_robot_nerve/spinal/src/spinal/board_configurator.py, aerial_robot_nerve/spinal/src/spinal/servo_monitor.py
Improve the parse process about the servo information based on rosparameter
The parse process about the joint name from the rosparameter is too ad-hoc.
We need to improve the condition to check the whether the rosparameter is about the servo.
=> [rqt_gui][rosparam] improve the parse process about the servo information based on rosparam

aerial_robot_nerve/stm32h7_nucleo/CMakeLists.txt
Update the cmake version for passing CI
=> [stm32h7_nucleo] correct the cmake version

aerial_robot_nerve/spinal/src/spinal/board_configurator.py, aerial_robot_nerve/spinal/src/spinal/servo_monitor.py
fix several potential bugs to run rqt script in python3 version.
=> [rqt][spinal] fix the compatibility in Python3

robots/hydrus/src/hydrus_tilted_lqi_controller.cpp
fix bug about thrust allocation in tilted robot
fix the formula for calculating thrust allocation
=> [Hydrus][Controller]Fix bug about thrust allocation in tilted robot

aerial_robot_kinetic.rosinstall, aerial_robot_melodic.rosinstall, aerial_robot_noetic.rosinstall
Add the PR info for the forked repositories
=> [rosinstall] add comment for the forked repositories

README.md, _config.yml, actuators.md
- Fix github pages URL
- Fix markdown processor for `jekyll serve`
- Added examination of ID setting for servo motor
=> update github pages

.github/PULL_REQUEST_TEMPLATE.md
Add a template file for PR, which is convenient for developers to carate new PR.
=> [Github] add template for pull-request

robots/hydrus_xi/CMakeLists.txt, robots/hydrus_xi/package.xml
Correct the dependent packages in CMakeLists.txt
=> [Hydrus_XI][CMake] refactor the dependent packages

.github/workflows/catkin_lint.yml, aerial_robot_base/config/sensors/lio/livox_mid360.yaml, aerial_robot_melodic.rosinstall, aerial_robot_noetic.rosinstall
Include  Livox ros driver and FAST LIO as thirdparty source for aerial_robot repository.
Update .rosinstall to automatically install livox_ros_dirver and fast lio
=> [Livox LiDAR + FAST LIO] enable to use Livox ros driver and FAST LIO as default 

aerial_robot_control/include/aerial_robot_control/flight_navigation.h, aerial_robot_control/src/flight_navigation.cpp
Improve the landing process to be more safe and precise.
-  Avoid the ascending motion in landing phase
-  Keep a minimum check duration for landing detection
-  Keep the target xy and yaw value between hovering and landing phases
=> [Navigation][Land] improve the landing process to be more safe and precise

.github/workflows/catkin_lint.yml, aerial_robot_melodic.rosinstall, aerial_robot_noetic.rosinstall
update rosinstall for melodic and noetic to latest ones
-  [JSKAerialRobot/aerial_robot_3rdparty](https://github.com/JSKAerialRobot/aerial_robot_3rdparty.git)
- [JSKAerialRobot/kalman_filter](https://github.com/JSKAerialRobot/kalman_filter.git)
- [JSKAerialRobot/sensor_interface](https://github.com/JSKAerialRobot/sensor_interface.git)
- [sugikazu75/mocap_optitrack](https://github.com/sugikazu75/mocap_optitrack.git)
=> [rosinstall] update external repositry versions

aerial_robot_control/src/flight_navigation.cpp
During following a trajectory, when the land command was published, the robot may disarm the motor suddenly.
=> [control][navigation] Skip following target_pose trajectory during landing

aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.cpp, aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.h, aerial_robot_nerve/neuron/neuronlib/Servo/servo.cpp, aerial_robot_nerve/neuron/neuronlib/Servo/servo.h, aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/servo/can_servo.cpp, aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/servo/can_servo.h
Refactor the torque off, especially the force torque off, rule, which should be determined by neuron.
- So far,  the force torque off, such as input voltage error, is determined by spinal. But it should be determined by neuron
- Overload error should not lead the servo off, since the algorithm of overload of dynamixel motor is wired.
=> [Spinal][Neuron][Servo] refactor the torque off rule 

aerial_robot_control/src/flight_navigation.cpp
There are several potential risks in the landing phase, including the lack of blocking new flight command
- Only accept new navigation command (e.g., new position ) in hover state 
- Force to reset the target velocity to zero in landing phase
=> [Navigation] refactor the process for landing phase. 

aerial_robot_nerve/neuron/neuron_f4/.gitignore
Update .gitignore to ignore Debug.launch generated from STM32CubeIDE
=> [Neuron][STM32F4] ignore unecessary build file from STM32CubeIDE

aerial_robot_model/src/utils/interactive_marker_tf_broadcaster.cpp
…ve marker tf broadcaster
set robot namespace for interactive marker.
=> [aerial_robot_model] fix frame name with robot namespace in interacti

aerial_robot_estimation/include/aerial_robot_estimation/state_estimation.h
Identify the namespace for `std::array`. 
When building with some external library, `array` without namespace cause collision.
=> [estimation] identify the name space std for std::array
