jsk-ros-pkg/jsk_aerial_robot

- motor_test/CMakeLists.txt
motor_test depends on takasako_sps. So far there is no explicit dependency for it in CMakeLists.txt. Now we add it.
> [Build Error: motor_test]: Add necessary dependency for motor_test

- aerial_robot.rosinstall
Since there is big change between indigo version and kinetic version about mavlink, and the aerial_robot_comm is based on the indigo version. We add the repository about mavlink in .rosinstall since we have to use indigo version for aeiral_robot_comm
> [Temporary] Use mavlink with indigo version 

- aerial_robot_control/src/flight_navigation.cpp
I fixed a bug that hydrus switches to pos_nav mode soon after it changed to acc_nav mode.
> fixed bug: enable acc nav mode

- aerial_robot_base/launch/external_module/mocap.launch
- aerial_robot_base/package.xml
- aerial_robot_kinetic.rosinstall
- aerial_robot_melodic.rosinstall
Currently, we update the version of  [Motive](https://www.optitrack.jp/products/software/optitrack/motive.html) from 1.7.3 (2015) to 2.2.0 (2019 final version) to support the latest product [Optitrack PrimeX13/13W](https://www.optitrack.jp/products/camera/primex13.html).
Fortunately, the update of ros package [mocap_optitrack](http://wiki.ros.org/mocap_optitrack) has caught up on the laster Motive version. So we can directly use the this official ros package instead of [the previous patched one](https://github.com/tongtybj/aerial_robot/blob/1.2.0/aerial_robot_kinetic.rosinstall#L13-L17).
I am still testing the official mocap_optitrack with different host PCs and robots, because I found the publish rate from Mocap PC (with Windows) to a Thinkpad PC significantly degrades (i.e., 100Hz -> …
> [WIP] update the usage of motion capture

- aerial_robot_base/launch/external_module/mocap.launch
The topic name of rigid object pose from optitrack is changed, so this remap is necessary.
> add topic remap in mocap.launch

- aerial_robot_base/config/sensors/gps/ublox_m9n.yaml
- aerial_robot_base/config/sensors/gps/ublox_rtk_m8p.yaml
- aerial_robot_base/launch/external_module/rtk_gps.launch
- aerial_robot_control/src/flight_navigation.cpp
- aerial_robot_estimation/include/aerial_robot_estimation/sensor/gps.h
- aerial_robot_estimation/include/aerial_robot_estimation/state_estimation.h
- aerial_robot_estimation/src/sensor/gps.cpp
- aerial_robot_kinetic.rosinstall
- aerial_robot_melodic.rosinstall
- robots/hydrus/launch/bringup.launch
Implement process to use RTK GPS in sensor fusion.
- Usage of RTK GPS can be found: 
https://github.com/tongtybj/aerial_robot_demo/blob/9fb5aa894b0b3788b931754db43fc3427bdf6d15/mbzirc2020/mbzirc2020_task1/mbzirc2020_task1_common/launch/bringup.launch#L48-L51
https://github.com/tongtybj/aerial_robot_demo/blob/9fb5aa894b0b3788b931754db43fc3427bdf6d15/mbzirc2020/mbzirc2020_common/launch/base_sensors.launch#L47
- Following hard-coding only allows RTK GPS registered as the second GPS module. This means there must be a normal GPS as the primal module:
https://github.com/tongtybj/aerial_robot/blob/6bd01bd1db7f46c643b47b09145492d2764890d4/aerial_robot_base/config/sensors/gps/ublox_rtk_m8p.yaml#L5
- Add rosparameter file for UBlox NEO M9N  module. We need to discuss about the sensor temporal …
> RTK GPS for sensor fusion

- aerial_robot_estimation/include/aerial_robot_estimation/sensor/plane_detection.h
- aerial_robot_estimation/src/sensor/plane_detection.cpp
Plane detection result always has offset against the ground truth.
When plane detection is enabled and alt sensor is disabled, the estimated height changes drastically resulting in an unstable flight.
When `dynamic_offset` is set to true, the offset is automatically calculated when plane_detection changes to ACTIVE state.
After the real machine experiment, I'll report the result. Then please merge this PR.
> Dynamic offset calculation in plane detection

- aerial_robot_control/src/flight_navigation.cpp
We need to set velocity to zero when change the flight navigation mode from `POS_VEL_MODE` to `POS_MODE`
> Fix bug about switching the flight navigation mode in x,y,z,yaw

- aerial_robot_kinetic.rosinstall
- aerial_robot_melodic.rosinstall
- aerial_robot_nerve/motor_test/README.md
- aerial_robot_nerve/motor_test/launch/test.launch
So far, we only support single type of force-torque sensor
> Support different series of force sensor for motor thrust test

- aerial_robot_control/src/control/fully_actuated_controller.cpp
The size of pseudo inverse matrix of `q_mat_` was wrong.
> Fix intialization bug for fully actuated control

- aerial_robot_nerve/spinal/src/spinal/board_configurator.py
- aerial_robot_nerve/spinal/src/spinal/servo_monitor.py
Fix the bug missed in #507 .
Correct the following python scripts in rqt gui:
- `map` -> `list(map)`
- `chr()` -> `[]` for `uint8 []`
- different cases for python2 and python3 for `ord()`
> Correct the python scripts for rqt gui to be compatible in ros noetic

- robots/dragon/config/MotorInfo.yaml
- robots/dragon/test/dragon_control.test
- robots/dragon/urdf/dragon_link.urdf.xacro
New link and rotor configuration for Dragon
Change battery for better flight performance:
[Turnigy 1300mAh 6S 35C Lipo](https://hobbyking.com/en_us/turnigy-1300mah-6s-35c-lipo-pack-450-helicopter-hk-trex-rave-e4-etc.html?queryID=&objectID=18141&indexName=hbk_live_products_analytics) => [Turnigy Bolt 1300mAh 6S 22.8V 65~130C LiHV](https://hobbyking.com/en_us/turnigy-bolt-1300mah-6s-22-8v-65-130c-high-voltage-lipoly-pack-lihv.html?queryID=&objectID=47548&indexName=hbk_live_products_analytics)
Please check this [website](https://www.rc-castle.com/index.php?route=product/product&product_id=8890&search=counter)
- propeller:  12 blades with  70mm duct
- rotor: freewing  2952 2100Kv Inrunner Brushless Motor
- ESC: [T-motor  60A](https://store.tmotor.com/goods.php?id=375)
- Lipo battery had a …
> [Dragon] update the rotor and link configuration 

- aerial_robot_model/script/solidedge_cog_inertia_tensor_converter.py
Fix the bug about the conversion of inertia tensor elements from SolidEdge result.
The sign of value `I_xy, I_xz, I_yz` should be negative.
> Fix the bug about the conversion of inertia tensor from SolidEdge

- aerial_robot_base/include/aerial_robot_base/aerial_robot_base.h
- aerial_robot_base/src/aerial_robot_base.cpp
Explicitly stop timer and async spinner for the safe destruction of AerialRobotBase
Without this patch, there is following error messsage when kill the aerial_robot_base node:
```bash
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```
> [aerial_robot_base]  Explicitly stop timer and async spinner for safe destruction

- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/Spine/spine.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/state_estimate/attitude/attitude_estimate.h
- robots/dragon/config/quad/egomotion_estimation/euclid_201709/FullVectoring.yaml
- robots/dragon/include/dragon/sensor/imu.h
- robots/dragon/src/sensor/imu.cpp
Add IIR LPF for IMU gyro data in the dragon imu sensor plugin
So far, we filtered the gyro data inside spinal to get filtered values for better control performance for DRAGON. However, this workaround need to occupy the magnetic data slot as follows:
https://github.com/jsk-ros-pkg/jsk_aerial_robot/compare/master...tongtybj:aerial_robot:PR/dragon/imu/lpf?expand=1#diff-39dac9e38e440c9379ca2db26aa1ac489801d3476b73c5e9de2fbb30164036c1L201
For better solution, we add new LPF in DRAGON::Imu sensor plugin,  which uses the  IIR filter to process raw gyro data. This can provide the same filtering performance with the workaround solution.
> [DRAGON] add IIR LPF for IMU gyro data

- aerial_robot_model/include/aerial_robot_model/servo_bridge.h
- aerial_robot_model/src/servo_bridge/servo_bridge.cpp
- aerial_robot_nerve/spinal/src/spinal/board_configurator.py
- aerial_robot_nerve/spinal/src/spinal/servo_monitor.py
- robots/dragon/config/quad/Servo.yaml
- robots/hydrus/config/quad/default_mode_201907/Servo.yaml
- robots/hydrus/config/quad/old_model_tx2_rs_t265_201906/Servo.yaml
- robots/hydrus/config/quad/old_model_tx2_zed_201810/Servo.yaml
- robots/hydrus/config/quad/tilt_10deg_15inch_202106/Servo.yaml
- robots/hydrus/config/quad/tilt_10deg_201907/Servo.yaml
- robots/hydrus/config/quad/tilt_20deg_201907/Servo.yaml
- robots/hydrus_xi/config/hex/Servo.yaml
- robots/hydrus_xi/config/hex_branch/Servo.yaml
- robots/hydrus_xi/config/quad/Servo.yaml
Improve the servo bridge process between spinal (spinal_ros_bridge) and ros system.
- introduce common ros topics  (servo states from spinal: `servo/states`, servo command to spinal: ` servo/target_states`) shared in different servo groups (e.g., joint, gimbal)
- classify servo (servo group) into three types: 
-  a) servo that shares the common topics (e.g. joint, gimbal with version after 1.3.0); 
- b)  servo that has no real state from spinal (e.g. gimbal with version before 1.3.0); 
- c) servo that has different topics (e.g. small servo for extra actuator), use boolean flag `no_real_state`.
Recently servo bridge process has a critical conflict/duplication between groups that uses same ros topics between servo_bridge and spinal_ros_bridge. This causes the failure for model that has …
> [Spinal] Improve the process of servo bridge

- .github/workflows/ros_test.yml
Currently rule in CI will cancel all in-progress jobs if any of jobs fails. 
ROS test for different ros distribution may have random failure becuase of the ros tests.
So allow to ignore failure from other jobs.
> [Github Action] do not cancel all in-progress in ros_test jobs.

- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp
Refactor the callback process in spinal from ros.
The callback invovling the `motor_number` should immediately quit if the value of `motor_number_` is zero.
These callback should process after the `motor_number_` is updated from rosi.
> [Spinal] refactor the callback process from rosserial

- aerial_robot_nerve/spinal/src/ros_lib/ros.h
The OUTPUT_SIZE for publisher in spinal size is too limited, so we cannot send large size message (e.g., servo state from all neurons). Incease to double size of 1024 bytes for sufficient space.
> [Spinal][rosserial] increase the size of OUTPUT_SIZE for publisher

- aerial_robot_simulation/include/aerial_robot_simulation/rotor_handle.h
In simulation, do not add noise if the target PWM is close to zero.
Current system add noise on target PWM to simulate the real rotor behabvior regardless of the PWM value. However, in real robot, if the PWM is zero, there is no noise.
> [Simulation][Rotor] do not add noise if the target PWM is close to zero 

- aerial_robot_estimation/src/sensor/mocap.cpp
The transport hint setting for mocap pose subscriber is broken. Refactor the setting rule for better use. 
Add `mocap/mocap_udp: true` in `StateEstimation.yaml` can switch to UDP mode if necessary.
StateEstimation.yaml for hydrus:
https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/robots/hydrus/config/quad/default_mode_201907/StateEstimation.yaml#L48-L49
> [Mocap] refactor the subscruber transport hint for pose subscriber

- aerial_robot_nerve/spinal/mcu_project/boards/stm32H7/Inc/main.h
use UART for spinal STM32H7 as default
STM32H7 support both UART and Ethernet for rosserial, and the previous default is Ethernet, which is minor case. So we change the default to UART for most of the common user.
> [Spinal][rosserial] use UART for STM32H7 as default

- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/Spine/spine.cpp
No CAN communication if there is no any Neuron found in initialization phase.
So far, Spinal will keep trying to contact with Neurons even if there is no any Neuron connected and detected. This will cause an very annoying message to rosserial "CAN is not connected". This PR patch avoids this message and also save the computation resource in spinal when Neurons are not connected.
> [Spinal][CAN] refactor the process when no neuron connected

- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp
Set the desired PWM output to timer handllers regardless of the CAN connection.
So far, we skip the output to Timer handler if we connect to CAN by "return", which make it very inconvenient to use TImer handler if we define the macro of "NERVE_COMM". 
This unneceesary skip should be removed.
> [Spinal][motor][PWM] set the desired PWM output to timer handllers 

- aerial_robot_nerve/neuron/neuronlib/CAN/can_constants.h
- aerial_robot_nerve/neuron/neuronlib/Initializer/initializer.cpp
- aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.cpp
- aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.h
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/initializer/can_initializer.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/Spine/spine.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/CAN/can_constants.h
- aerial_robot_nerve/spinal/scripts/servo_rough_calib.py
- robots/dragon/launch/includes/euclid_201709/sensors.launch.xml
This PR can compensate the round offset between servo and joint. 
The joint pulley may make an undesired round offset between servo abs encoder and joint real angle. 
For example, in case of  a pulley ratio of 1:2 (servo:joint), the servo encoder need a true value over 360 deg for joint angle with more than 180 deg. But the abs encoder  can only have an initial value around 0~360 deg, which means the abs encoder will give a very small initial value theta for joint angle more than 180 deg.  
This PR enables manual compensation by user with rosservice of `Spinal/SetBoardConfig`. Command ID is `11`, and the command data should be `[slave_id, servo_index, compensate_servo_angle]`.
We also provide an automatic compensate code:
```
$ rosrun spinal servo_rough_calib.py
```
This will …
> [Spinal][Neuron][Servo] solve the joint pulley round offset problem

- robots/hydrus_xi/CMakeLists.txt
- robots/hydrus_xi/package.xml
package of `aerial_robot_simualtion` should only be an `exec_dependency` for launch file, but not a `build_dependency`.
> [Hydrus XI] refactor the description about dependency

- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/Spine/spine.cpp
No PWM command to CAN system  if there is no neuron detected. 
This bug induce the invliad access to non-exist pointer.
> [Spinal][CAN] fix bug about the motor pwm in spinal-neuron system

- aerial_robot_control/include/aerial_robot_control/flight_navigation.h
- aerial_robot_control/src/flight_navigation.cpp
Debug in landing, halt command in XyControlMode =VEL_CONTROL_MODE, and ACC_CONTROL_MODE
- set POS_CONTROL_MODE when navigator get landing, halt topic
- setTargetAcc = 0 in setTargetXyFromCurrentState
> [Aerial Robot Control] landing, halt command during vel acc-based mode

- aerial_robot_estimation/include/aerial_robot_estimation/sensor/vo.h
- aerial_robot_estimation/src/sensor/vo.cpp
Revert the throttle/decimate process inside the callback process, which allows to set larger interval between two valid data from VO sensor.
Some of the VO sensors (e.g., Realsense T265) provides the odometry with a high frequency that is unecessary for our fusion system. So, a simple decimation process is designed here.
> [Estimation][VO] Refactor throttle/decimate process

- aerial_robot_model/src/model/plugin/multirotor_robot_model.cpp
- aerial_robot_model/src/model/plugin/underactuated_tilted_robot_model.cpp
- robots/dragon/include/dragon/control/full_vectoring_control.h
- robots/dragon/include/dragon/model/full_vectoring_robot_model.h
- robots/dragon/src/control/full_vectoring_control.cpp
- robots/dragon/src/model/full_vectoring_robot_model.cpp
There is a bug while assigning the arg to the variable `fixed_model_` while creating the instance for underactuated model.
- Forget to assign the boolean value for `fixed_model_` when creating the instance for underactuated model plugin.
- Use `aerial_robot_model::transformable::RobotModel` instead of `aerial_robot_model::RobotModel` for planning in dragon model and control processes.
> [Aerial Robot Model][Underactuated][Plugin] fix the wrong args assignment for model constructor

- aerial_robot_base/src/aerial_robot_base.cpp
- aerial_robot_control/include/aerial_robot_control/flight_navigation.h
- aerial_robot_control/src/control/base/pose_linear_controller.cpp
- aerial_robot_control/src/flight_navigation.cpp
- aerial_robot_estimation/include/aerial_robot_estimation/sensor/imu.h
- aerial_robot_estimation/include/aerial_robot_estimation/state_estimation.h
- aerial_robot_estimation/src/sensor/altitude.cpp
- aerial_robot_estimation/src/sensor/imu.cpp
- aerial_robot_estimation/src/state_estimation.cpp
- robots/dragon/include/dragon/dragon_navigation.h
- robots/dragon/src/dragon_navigation.cpp
- robots/hydrus_xi/include/hydrus_xi/hydrus_xi_under_actuated_navigation.h
- robots/hydrus_xi/src/hydrus_xi_under_actuated_navigation.cpp
Improve the landing motion with a uniform descending motion 
- Previous landing process is very tricky and can only land with the initial (takeoff) height.
- Enable to land with a constant veloity which can be set by rosparam: https://github.com/jsk-ros-pkg/jsk_aerial_robot/compare/master...tongtybj:develop/landing_process?expand=1#diff-9c1ce395efa7ef3a077e6e1471de383649423c7453dd7c227c41adf5fd490eb8R857
- Enable to land with arbitray height, whcih check the steady state by https://github.com/jsk-ros-pkg/jsk_aerial_robot/compare/master...tongtybj:develop/landing_process?expand=1#diff-9c1ce395efa7ef3a077e6e1471de383649423c7453dd7c227c41adf5fd490eb8R716-R717.
> [Navigation] improve the landing motion for all robots

- aerial_robot_base/scripts/keyboard_command.py
- aerial_robot_base/src/aerial_robot_base.cpp
- aerial_robot_control/include/aerial_robot_control/flight_navigation.h
- aerial_robot_control/src/control/base/pose_linear_controller.cpp
- aerial_robot_control/src/flight_navigation.cpp
- aerial_robot_estimation/include/aerial_robot_estimation/sensor/imu.h
- aerial_robot_estimation/include/aerial_robot_estimation/state_estimation.h
- aerial_robot_estimation/src/sensor/altitude.cpp
- aerial_robot_estimation/src/sensor/imu.cpp
- aerial_robot_estimation/src/state_estimation.cpp
- robots/dragon/include/dragon/dragon_navigation.h
- robots/dragon/src/dragon_navigation.cpp
- robots/hydrus_xi/include/hydrus_xi/hydrus_xi_under_actuated_navigation.h
- robots/hydrus_xi/src/hydrus_xi_under_actuated_navigation.cpp
refactor the navigation part to allow the uniform linear motion from teleoperation
- allow to use joystick and keyboard to control the robot with uniform linear motion (constant velocity)
- refactor the keyboard script to be friendly for beginner.
> [Navigation][merge after #554] improve teleoperation process

- aerial_robot_estimation/include/aerial_robot_estimation/sensor/gps.h
- aerial_robot_estimation/src/sensor/gps.cpp
"register" specifier is depreacated, and is not allowed in c++17.
"register": https://www.ibm.com/docs/en/zos/2.2.0?topic=specifiers-register-storage-class-specifier
Besides,  the calculation of GPS time conversion is light enough, thus register storage should be unnecessary.
> [GPS] remove "register" specifier for GPS time calculation. 

- .travis.sh
- aerial_robot_base/CMakeLists.txt
- aerial_robot_control/CMakeLists.txt
- aerial_robot_estimation/CMakeLists.txt
- aerial_robot_kinetic.rosinstall
- aerial_robot_melodic.rosinstall
- aerial_robot_model/CMakeLists.txt
- aerial_robot_noetic.rosinstall
- aerial_robot_simulation/CMakeLists.txt
- robots/dragon/CMakeLists.txt
- robots/hydrus/CMakeLists.txt
- robots/hydrus_xi/CMakeLists.txt
Since C++17 is quite standard recently, we are going to update CMakeLists.txt in all related pakages.
- For ubuntu xenial, we manually install `g++-7` to use C++17. Please check https://github.com/tongtybj/aerial_robot/blob/c12acebe8a7453efc47700a9a844499e7e586502/.travis.sh#L62-L70
- Related work: https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/573
> [CMake] using C++17 for related packages

- aerial_robot_control/src/flight_navigation.cpp
Imrpove the landing convergence condition for faster motor disarming.
- allow the positive landing velocity in final landing convergence check 
- make the default `land_vel_convergent_thresh` larger
- make the default `land_check_duration` shorter
> [Navigation][Land] refactor the landing convergence condition 

- aerial_robot_control/src/control/base/pose_linear_controller.cpp
Initiailization of `force_landing_descending_rate` is missing in current branch.
> [Control][Landing][Bug]  revert the missing initialization for variable about force landing

- aerial_robot_control/include/aerial_robot_control/flight_navigation.h
- aerial_robot_control/src/flight_navigation.cpp
failsafe for high input voltage
If input voltage is higher than nominal voltage by threshold, robot can not arm on.
Threshold can be set by rosparam
> [navigation] failsafe for high input voltage

- aerial_robot_estimation/src/sensor/mocap.cpp
Topic of `ground_truth` which is published from gazebo node has a severe delay problem when subscrbing in the mocap plugin. We use a explicit option `tcpNoDelay` to solve this delay. 
- This topic is published from [aerial_robot_hw_sim.cpp](https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_simulation/src/aerial_robot_hw_sim.cpp#L196), and is subscribed in [mocap.cpp](https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_estimation/src/sensor/mocap.cpp#L83). 
- Only this topic has a severe delay problem, other similar topics such as [mocap/pose](https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_simulation/src/aerial_robot_hw_sim.cpp#L197), has no such delay problem.
> [Gazebo][Mocap][Subscriber] solve the topic delay related to the ground_truth pose

- aerial_robot_nerve/spinal/mcu_project/boards/stm32H7/Src/main.c
The initialization and add order of spinal-IMU is wrong. This should be done before initializing Spinal.
> [Spinal][STM32H7] correct the initialization order of spinal-IMU

- aerial_robot_estimation/include/aerial_robot_estimation/sensor/vo.h
- aerial_robot_estimation/src/sensor/vo.cpp
refactor the process of KF based estimation with visual odometry
Please explain the contribution of this PR in detail.
- refactor the transform from the world frame to the orgin frame of vo/vio
- refactor the process for velocity to the reference frame
- add static tf frome the world frame to the vo origin frame
> [Estimation][VO/VIO] refactor the process of KF based estimation with visual odometry

- aerial_robot_estimation/src/sensor/imu.cpp
Refactor the index designation of KF based estimation result
use "for" function to assign the result of KF result for different estimation mode.
> [Estimation][IMU] refactor the index designation of KF based estimation result

- aerial_robot_base/launch/external_module/mocap.launch
Remove the "required" flag in the launch flie to allow the onboard-sensor-only flight
> [Mocap] improve the launch parameter

- aerial_robot_nerve/spinal/package.xml
- robots/dragon/package.xml
- robots/hydrus_xi/package.xml
Fixed bug when building  each package independently.
- spinal
- should run_depend on `rosserial_client`.  
- https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_nerve/spinal/scripts/make_libraries.py#L45
- hydrus_xi
- should depend on nlopt and osqp-eigen
- https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/robots/hydrus_xi/CMakeLists.txt#L13-L14
- dragon
- should depend on nlopt 
- https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/robots/dragon/CMakeLists.txt#L22
> [Package.xml] Resolve dependency to other package

- aerial_robot_nerve/motor_test/CMakeLists.txt
- aerial_robot_nerve/motor_test/package.xml
- aerial_robot_nerve/motor_test/src/motor_test.cpp
- aerial_robot_nerve/spinal/CMakeLists.txt
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.h
- aerial_robot_nerve/spinal/msg/PwmTest.msg
Change some structure of the PWM test to support motor-by-motor check
- Send PWM value (0.55) to all motors simultaneously
- ```rostopic pub -1 /pwm_test spinal/PwmTest "motor_index: [] pwms: [0.55]"```
- Send PWM value (motor 0 → 0.55, motor 2 → 0.65) independently
- ```rostopic pub -1 /pwm_test spinal/PwmTest "motor_index: [0,2] pwms: [0.55, 0.65]"```
- Escape from PWM test mode
- ```rostopic pub -1 /pwm_test spinal/PwmTest "motor_index: [] pwms: []"```
> [Spinal][PwmTest] workaround to send pwm value to each servo independependently

- .github/workflows/ros_test.yml
We have removed the kinetic ros-distribution from the list of Github Action workflows, becuase it is so legacy that `rosdep update` cannot be executed properly.
> [CI][Github Action] stop the support of kinetic ros-distribution

- aerial_robot_control/include/aerial_robot_control/trajectory/trajectory_reference/polynomial_trajectory.hpp
- aerial_robot_control/src/flight_navigation.cpp
- aerial_robot_control/src/trajectory/trajectory_reference/polynomial_trajectory.cpp
The yaw angle has the discontinued problem around PI. This PR solve the wrong rotation path in trajectory generation, that is, the trajectory must choose the shortest path. 
This is achieved by checking diff angle with previous yaw angle, and add an offset to remove a big gap 
```
if (diff > M_PI) yaw_angle -= 2 * M_PI;
if (diff < -M_PI) yaw_angle += 2 * M_PI;
```
> [Navigation][Trajectory] solve the discontinued problem of yaw rotation

- aerial_robot_nerve/neuron/neuronlib/Initializer/initializer.cpp
- aerial_robot_nerve/neuron/neuronlib/Servo/servo.cpp
- aerial_robot_nerve/neuron/neuronlib/Servo/servo.h
Do not accept any message from spinal, if neuron has not sent the initalize information to spinal.
This can avoid a corner case of the unexpected behavior of servo after updating the firmware of neuron while spinal and neurons are already connected by CAN.
- This is achieved by introducing a new variable `connect_`
- Neuron servo instance never accept any message from spinal via CAN if `connect_` is false
- `connect_` can be true only after neuron has sent the necessary information to spinal.
> [Neuron][Servo][Initialize] introduce a new variable to check the connection between spinal and neuron

- aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.cpp
The commit of [75bd140](https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/636/commits/75bd14085b608e480dc4d9192fe5c144e4e85aac) is advanced for current master version, which is based on unmerged PR of #527. 
So I just simply revert this commit.
> [Neuron][Servo] fix bug due to #636

- aerial_robot_nerve/neuron/neuronlib/Servo/servo.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/initializer/can_initializer.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/initializer/can_initializer.h
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/Spine/spine.cpp
Solve the corner case due to the error of servo motor connected to the neuron, which requires the force reboot of the neuron from spinal.
- Send `force_torque_off` as `true` is the neuron is not ready to connect with spinal. This is the corner case that the neuron is manually rebooted by spinal, but the neuron does not send the initial config to the spinal.
- Recall the config request from spinal to the rebooted neuron after the reboot is finish.
> [Spinal][Neuron] refactor the initialization/reinitialization process

- aerial_robot_base/bin/install_igmp_report.sh
- aerial_robot_base/scripts/send_igmp_report.py
Force to send a IGMP report (respnse) message from client (e.g., robot, pc) to router to keep the connection for multicast.
- `send _import_report.py` sends the IGMP report message. However, we need to execute this script with root permission becuase of the usage of the raw socket API. Therefore the command without root permission (e.g., `rosrun`) requires password every time, which makes the operation not elegant.
- `install_igmp_report.sh`: that's why I create this file to install the above python file in `crontab` under root, which allows the system to run the python file periodicaly (i.e., every two min).
Just run following command once in your pc or robot that needs mocap data.
```bash
$ rosrun aerial_robot_base install_igmp_report.sh
```
> [Mocap][Multicast] solve the mocap disconnection problem becuase of  IGMP protocol

- configure.sh
Change the URL of repository for ros one packages to https://github.com/v4hn/ros-o-builder/tree/jammy-one-unstable
> [ROS-One] change the repository from forked one (kazuki) to the orignal one (v4hn)

- .github/workflows/spinal_build.yml
This PR provides a Github Action workflow that automatically builds Spinal firmware by Github Action.
This workflow runs in a docker image where ros noetic and STM32CubeIDE are installed. 
Dockerfile is now located [here](https://github.com/sugihara-16/Spinal_build_docker_image) and you can download the built image with the following command:
`$ docker pull ghcr.io/sugihara-16/docker_test/stm32cubeide_1.8.0_build_env:2024-11-03`
Additionally, you can find example of generated files [here](https://github.com/sugihara-16/aerial_robot/actions/runs/11653477001).
> [Spinal][Github Action] Automatic Spinal  firmware build flow by Github Action.

- aerial_robot_nerve/motor_test/scripts/analyze_data.py
- aerial_robot_nerve/motor_test/src/motor_test.cpp
Add a Python script to analyze the motor_test data. Aim to replace the excel we used.
**usage**: `python analyze_data.py [-h] [--set_voltage SET_VOLTAGE] [--folder_path FOLDER_PATH] file_name has_telemetry`
**positional arguments**:
file_name             file name
has_telemetry         has telemetry, 0 or 1
**optional arguments**:
-h, --help            show this help message and exit
--set_voltage SET_VOLTAGE
the voltage set in the test, float
--folder_path FOLDER_PATH
path to folder
The default folder path is '~/.ros/'
Usage Demo: 
`python analyze_data.py u=25.20v_motor_test_1706621604.txt 1`
> [SYSID] [Motor Test] add a py script to analyze motor_test data

- .github/workflows/catkin_lint.yml
Explictly specify the distribution of ubuntu (20.04) to avoid the random failure of installation of `python3-wstool`.
- `sudo` is not required 
- `DEBIAN_FRONTEND=noninteractive` is required to avoid the unexpected wait for installation of `tzdate`
> [GA][Catkin Lint] refactor the script to run catkin lint

- .github/workflows/spinal_build.yml
The ros header files for spinal `ros_lib`  are always build incorrectly, because the multiple processes (and multiple jobs) in CI cannot perform pefectly. Therefore, it is necessary to explicitly speficy the build option wtin single process and single job.
The failure of  `ros_lib` is due to the imcomplete build of the ros messages if multiple processes are allowed in CI. One of the exmaple is https://github.com/jsk-ros-pkg/jsk_aerial_robot/actions/runs/12523073205/job/35008028809#step:5:235.
> [GA][Firmware Build] refactor the catkin build option to avoid the message generation error

- aerial_robot_estimation/src/state_estimation.cpp
Stop broadcasting TF if the timestamp is identical with the last one.
Please explain the contribution of this PR in detail.
- The TF server will generate annoying warning message if there is broadcaster that send TF with same timestamp as shown in the following image.
- This might happen for our system especially in simulation mode, since the TF from `world` to `root` uses the timestamp provided by IMU.
> [Estimation] stop broadcasting redundant TF with same timestamp

- robots/dragon/include/dragon/dragon_navigation.h
- robots/dragon/src/control/lqi_gimbal_control.cpp
- robots/dragon/src/dragon_navigation.cpp
DRAGON needs to make the body level before entering the landing phase. This was achieved by using an additional flag `landing_flag`, and the flight state was temporarily back to `HOVER_STATE` to make the body level. However, this is a special phase and the robot should not receive any navigation command which would hinder the leveling motion. Therefore,  a new state called `PRE_LAND_STATE` is introduced to handle this special phase.
- remove `landing_flag` , and replace with new fligtht state `PRE_LAND_STATE`
- modify the leveling process with new fligtht state `PRE_LAND_STATE`
- modify other related control parts that depended on `landing_flag`
> [Dragon][Naviagation] refactor the landing process

- aerial_robot_model/include/aerial_robot_model/model/aerial_robot_model.h
Add new API to get and set extra module map.
These API is required to set exrra module map state in ROS-related model to other robot model instance (e.g. `robot_model_for_control_` in dragon)
> [aerial_robot_model] add new API to get and set extra module map

- .github/workflows/firmware_build.yml
Since the docker file for firmware build is rarely updated. The list of debian packages might be old.
So it is necessary to update the list by `apt update` at the beginning of CI
Please briefly explain the purpose and the result of this PR.
- problem:  https://github.com/jsk-ros-pkg/jsk_aerial_robot/actions/runs/12831193462/job/35807420902#step:4:123
- reason: docker file is not updated but the URL of debian package is updated. 
- solution: update the list by `apt update`
> [GA][Firmware Build] udpate the debian list at the beginning 

- aerial_robot_control/include/aerial_robot_control/flight_navigation.h
- aerial_robot_control/src/flight_navigation.cpp
More safety takeoff
We should not allow robots to takeoff when initial pos errror is so large. This can be happened when egomotion estimation is wrong.
- show tagret height and xy pos
- disable takeoff when  initial xy pos error is larger than threshold 
https://github.com/user-attachments/assets/149909e9-0c6b-465b-a6d1-f40d5d2a4b38
> [navigation] disable takeoff if initial xy pos error is larger than threshold

- aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.cpp
- aerial_robot_nerve/neuron/neuronlib/Servo/Dynamixel/dynamixel_serial.h
- aerial_robot_nerve/neuron/neuronlib/Servo/servo.cpp
- aerial_robot_nerve/neuron/neuronlib/Servo/servo.h
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/servo/can_servo.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Hydrus_Lib/CANDevice/servo/can_servo.h
update and send goal postion from neuron to spinal to handle sync problem when using external encoder.
- new goal position after the servo toruqe turning on is determined by neuron, and is sent to spinal to replace with the old goal position in it.
- the goal position and the present position share the same slot from neuron to spinal to save the limited bandwidth of CAN.
- acknowledge flag is introduced to handle the mode switch between goal poisiton sending and present position sending.
- the torque enable flag is shifted from `CAN::MESSAGEID_RECEIVE_SERVO_ANGLE` to `CAN::MESSAGEID_RECEIVE_SERVO_CURRENT`
> [Servo][Spinal][Neuron] send goal postion from neuron to spinal to solve the sync problem between them when using external encoder

- aerial_robot_model/src/model/base_model/robot_model.cpp
- aerial_robot_model/src/model/transformable_model/stability.cpp
To calculate distance from orign to the surface of feasible control convex, we need to consider the norm of cross production between two vector, and use it to devide the third vector. Therefore, the norm should not be zero which is the singualr case when two vectors are almost paralell.
- Please refere to  Eq.17 in https://arxiv.org/pdf/2008.05613. The norm of `(v_i x v_j)` should not be zero. This means it becomes singualr when `v_i` and `v_j` are paralell.
- We introduce a small value about 10e-5 to determine whether the norm is almost zero.
- Corresponding rostest is performed in [hydrus_xi_jacobian.test](https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/robots/hydrus_xi/test/hydrus_xi_jacobian.test#L41)
> [Feasible Control Convex] [Jacobian] refactor singularity handle with two unit vectors are almost paralell 

- aerial_robot_control/include/aerial_robot_control/flight_navigation.h
- aerial_robot_control/src/flight_navigation.cpp
The operation about trajectory generator is distributed several thread. To achieve the exclusive control, whether the pointer of trajectory generator is empty is checked every time. 
- The pointer of trajectory generator is empty is checked before using the related API. [Example](https://github.com/jsk-ros-pkg/jsk_aerial_robot/compare/master...tongtybj:aerial_robot:PR/navigation/trajectory_reset?expand=1#diff-9c1ce395efa7ef3a077e6e1471de383649423c7453dd7c227c41adf5fd490eb8R1026-R1032).
> [Navigation][Trajectory] avoid the wrong access to empty trajectory generator just after reset

- robots/hydrus_xi/test/hydrus_xi_hex_branch_control.test
- robots/mini_quadrotor/test/flight_control.test
The privous delay (i.e. 2sec) for sending task start topic is too shut for the gazebo initialization. Therefore increase it to 5 sec.
Related issue: https://github.com/jsk-ros-pkg/jsk_aerial_robot/pull/671#issuecomment-2660897536
> [Rostest][Timeout] increase the delay for sending task start trigger for mini_quadrotor and hydrus_xi

- aerial_robot_base/src/aerial_robot_base/state_machine.py
- aerial_robot_control/CMakeLists.txt
- aerial_robot_control/include/aerial_robot_control/util/joy_parser.h
- aerial_robot_control/src/flight_navigation.cpp
- aerial_robot_control/src/util/joy_parser.cpp
Refactor the conversion of joy command, and support more types of joy controller
- extract the joy conversion function to independent file:s `aerial_robot_control/include/aerial_robot_control/util/joy_parser.h` and `aerial_robot_control/src/util/joy_parser.cpp`
- support other joy controller to do navigation and smach based simple demo 
- ps4-like bluetooth joy controller:
- support common RoG Ally:
> [Navigation] refactor the joy command receiver to support more types of joy controller

- .github/workflows/ros_test.yml
- robots/mini_quadrotor/test/CMakeLists.txt
Add arm64 architecture in github action to enable test for arm-based computer.
- Update matrix in github action to support both x64 and arm64 archs.
- Skip mujoco-based simulation in arm64 archs.
> [CI][Architecuture] suport test on arm64 architecture

- aerial_robot_base/src/aerial_robot_base.cpp
Added explicit stop() call of callback_spinner_ in deconstructor of AerialRobotBase class as done for main_loop_spinner_
Please explain the contribution of this PR in detail.
- PR/add_stop_decl: added stop() call in deconstructor ~AerialRobotBase()
> Explicitly deconstructing

- aerial_robot_estimation/src/sensor/altitude.cpp
The cmake build process gives the following warning:
"jsk_aerial_robot/aerial_robot_estimation/src/sensor/altitude.cpp:583:5: warning: control reaches end of non-void function [-Wreturn-type]"
Which means there is a logical path in the function "bool terrainProcess()" where there is no return statement.
Added a default "return false" for the ABNORMAL case where the recovering process didn't succeed and the altitude measurement is faulty.
Please check if my reasoning is correct!
> Missing return statement in logic for altitude sensor

- aerial_robot_nerve/spinal/bin/cube_ide.sh
The latest version of spinal firmware 4.1 has not been updated in cube_ide.sh, so I update it.
To use it:
`rosrun spinal cube_ide.sh stm32H7_v2`
Just for clarification: after the PR #630, we should use stm32H7_v2 for Spinal v4.1, right? The newly supported function includes the DShot protocol and direct servo control. Is my understanding correct? @sugihara-16
> [Spinal] update the cube_ide.sh to launch stm32H7_v2 for spinal v4.1

- aerial_robot_estimation/CMakeLists.txt
Explicitly add dependency of aerial_robot_estimation for sensor_pluginlib
Several sensor plugins use the API of  state_estimation. For example:
```
chou@chou-ThinkPad-P14s-Gen-4:~/ros/jsk_aerial_robot/src/jsk_aerial_robot/aerial_robot_estimation$ grep "setOrientationWxB" * -r
include/aerial_robot_estimation/state_estimation.h:    void setOrientationWxB(int frame, int estimate_mode, tf::Vector3 v);
src/state_estimation.cpp:void StateEstimator::setOrientationWxB(int frame, int estimate_mode, tf::Vector3 v)
src/sensor/vo.cpp:        estimator_->setOrientationWxB(Frame::BASELINK, EGOMOTION_ESTIMATE, wx_b);
src/sensor/vo.cpp:        estimator_->setOrientationWxB(Frame::COG, EGOMOTION_ESTIMATE, wx_c);
src/sensor/mocap.cpp:          estimator_->setOrientationWxB(Frame::BASELINK, …
```
> [Estimation] explicitly add dependency of aerial_robot_estimation for sensor_pluginlib

- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/servo/drivers/Dynamixel/dynamixel_serial.cpp
Since the command of `set_goal_pos` does not require the return packet, so use sync mode for any situations (either )
- No matter whether `ttl_rs485_mixed` is activated, the command of `set_goal_pos`  use `cmdSyncWriteGoalPosition();`: https://github.com/tongtybj/aerial_robot/blob/c13027256db14e9e88dd502dbde99ffb024a6b74/aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/servo/drivers/Dynamixel/dynamixel_serial.cpp#L372
- Thus, following process is redundant and consume the bandwidth:
```bash
for (unsigned int i = 0; i < servo_num_; ++i) {
instruction_buffer_.push(std::make_pair(INST_SET_GOAL_POS, i));
}
```
- Related PR: https://github.com/sugihara-16/aerial_robot/pull/15
> [Spinal][Servo][Dynamixel] fix the bug about the command sending process for  goal position

- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/configs/STM32H7/config.h
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/configs/STM32H7_v2/config.h
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/servo/drivers/Dynamixel/dynamixel_serial.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/servo/drivers/Dynamixel/dynamixel_serial.h
Automatically detect the connection mode between standard UART (using TTL2DXIF) and half-duplex (direct TTL)
- abolish the manual designation using macro `DYNAMIXEL_BOARDLESS_CONTROL`
- introduce a new variable `direct_ttl_mode_` to distinguish between full duplex and half duplex.
- refactor `pinReconfig()` funciton to automatically detect the correct mode.
- already confirmed the expected performace with four servo mtors.
> [Spinal][Servo][Dynamixel] automatically detect the connection mode

- aerial_robot_nerve/neuron/neuronlib/CAN/can_device_manager.cpp
- aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/CAN/can_device_manager.cpp
The previous counter reset at 999ms, which is fixed by remove `-1`.
> [CAN][Spinal][Neuron] correct the tick to count 1 second
